version: '3'

services:
  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/loki
    networks:
      - app-network
  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./promtail/config:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki
  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - registry-service
      - gateway-service
      - auth-service
      - account-service
      - product-service
  grafana:
    image: grafana/grafana-oss:10.2.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus
      - loki
  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - registry-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - registry-service
      - account-bd
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - POSTGRES_URL=account-bd
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=MSA_account_db
  account-bd:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MSA_account_db
    networks:
      - app-network
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - registry-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - registry-service
      - product-bd
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - POSTGRES_URL=product-bd
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=MSA_product_db
  product-bd:
    image: postgres
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MSA_product_db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge