version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    environment:
      RABBIT_URL: http://guest:guest@rabbitmq:15672
    ports:
      - "9419:9419"
    networks:
      - app-network
    depends_on:
      - rabbitmq
  loki:
    image: grafana/loki:3.2.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/loki
    networks:
      - app-network
  promtail:
    image: grafana/promtail:3.2.1
    volumes:
      - ./promtail/config:/etc/promtail
      - ./logs:/var/log/microservices_logs:rw
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki
      - registry-service
      - gateway-service
      - auth-service
      - account-service
      - product-service
  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - registry-service
      - gateway-service
      - auth-service
      - account-service
      - product-service
  grafana:
    image: grafana/grafana-oss:10.2.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus
      - loki
  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    volumes:
      - ./logs/registry-service:/var/log/registry-service
    ports:
      - "8761:8761"
    networks:
      - app-network
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    volumes:
      - ./logs/gateway-service:/var/log/gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - registry-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    volumes:
      - ./logs/account-service:/var/log/account-service
    networks:
      - app-network
    depends_on:
      - registry-service
      - account-bd
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - POSTGRES_URL=account-bd
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=MSA_account_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  account-bd:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MSA_account_db
    networks:
      - app-network
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./logs/auth-service:/var/log/auth-service
    networks:
      - app-network
    depends_on:
      - registry-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    volumes:
      - ./logs/product-service:/var/log/product-service
    networks:
      - app-network
    depends_on:
      - registry-service
      - product-bd
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka
      - POSTGRES_URL=product-bd
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=MSA_product_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  product-bd:
    image: postgres
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MSA_product_db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge