global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-cloud-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'registry-service:8761', 'gateway-service:8080', 'auth-service:8082', 'account-service:8081', 'product-service:8083' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'promtail'
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq-explorer:9419' ]