spring:
  application:
    name: gateway-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    gateway:
      routes:
        - id: account-service-api-docs
          uri: lb://account-service
          predicates:
            - Path=/account-service/v3/api-docs
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: POST
                    path: /api/v1/accounts/register
                  - method: POST
                    path: /api/v1/accounts/login
                  - method: POST
                    path: /api/v1/accounts/refresh-token
        - id: product-service-api-docs
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: GET
                    path: /api/v1/products
                  - method: GET
                    path: /api/v1/categories
                  - method: GET
                    path: /api/v1/ingredients
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  file:
    name: /var/log/${spring.application.name}/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Account Service
        url: /account-service/v3/api-docs
      - name: Product Service
        url: /product-service/v3/api-docs