spring:
  application:
    name: gateway-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: POST
                    path: /api/v1/accounts/register
                  - method: POST
                    path: /api/v1/accounts/login
                  - method: POST
                    path: /api/v1/accounts/refresh-token
                  - method: GET
                    path: /api/v1/accounts/api-docs
                  - method: GET
                    path: /api/v1/accounts/swagger-ui
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: GET
                    path: /api/v1/products
                  - method: GET
                    path: /api/v1/categories
                  - method: GET
                    path: /api/v1/ingredients
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/v1/addresses/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: GET
                    path: /api/v1/addresses/districts
                  - method: GET
                    path: /api/v1/addresses/api-docs
                  - method: GET
                    path: /api/v1/addresses/swagger-ui
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - name: CustomAuthFilter
              args:
                excludedPaths:
                  - method: GET
                    path: /api/v1/addresses/api-docs
                  - method: GET
                    path: /api/v1/addresses/swagger-ui
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  file:
    name: /var/log/${spring.application.name}/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"