spring:
  application:
    name: gateway-service
  cloud:
    gateway:
        routes:
          - id: account-service
            uri: lb://account-service
            predicates:
              - Path=/api/v1/account/**
            filters:
              - name: CustomAuthFilter
                args:
                  validatePath: http://auth-service/api/v1/auth/validate-token
                  excludedPaths: /api/v1/account/register,/api/v1/account/login
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - name: BlockPublicAccessFilter
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}