server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "registry-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "registry-service"
          path: /var/log/microservices_logs/registry-service/*.log

  - job_name: "gateway-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "gateway-service"
          path: /var/log/microservices_logs/gateway-service/*.log

  - job_name: "auth-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "auth-service"
          path: /var/log/microservices_logs/auth-service/*.log

  - job_name: "account-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "account-service"
          path: /var/log/microservices_logs/account-service/*.log

  - job_name: "product-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "product-service"
          path: /var/log/microservices_logs/product-service/*.log