server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "registry-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "registry-service"
          __path__: "/var/log/microservices_logs/registry-service/registry-service.log"

  - job_name: "gateway-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "gateway-service"
          __path__: "/var/log/microservices_logs/gateway-service/gateway-service.log"

  - job_name: "auth-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "auth-service"
          __path__: "/var/log/microservices_logs/auth-service/auth-service.log"

  - job_name: "account-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "account-service"
          __path__: "/var/log/microservices_logs/account-service/account-service.log"

  - job_name: "product-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "product-service"
          __path__: "/var/log/microservices_logs/product-service/product-service.log"

  - job_name: "address-service"
    static_configs:
      - targets: [ ]
        labels:
          job: "address-service"
          __path__: "/var/log/microservices_logs/address-service/address-service.log"